### ISSUE TITLE
Implement an automated way to exclude non-brain channels from Jacksheet

### ISSUE THREAD

**Issue by ramdarpaproject** [pennmem/bptools#7]

**Comment by mivade** [comment]
ECG/EKG channels are already excluded, and it looks for "good_leads.txt" to only include those that have already been labeled as good. I don't think it can be more automated than that (assuming good_leads.txt is generated automatically in the neurorad pipeline).

**Comment by mivade** [comment]
Closing for now since this hasn't come up as a problem anywhere.
